### PR TITLE
Added cyclically expansive learning wrapper

### PR DESCRIPTION
**Pull request by lssr**
I did not bump the version.

### CODE REVIEW

**Comment by weepingwillowben** [comment]
This needs:

1. Documentation in readme.md
2. At least a basic test in aec_mock_test.py
3. This default is a little off. The schedule should be on a much longer scale than a thousand steps. Perhaps there should not be a default at all and just an example in the readme.

**Comment by lssr** [comment]
- Added documentation in readme.md.
- Included a basic test in aec_mock_test.py.
- Removed default curriculum.

**Comment by weepingwillowben** [comment]
So tests are failing because of some upstream changes in PettingZoo. I fixed master, so if you merge with master then tests should pass again.

**Comment by weepingwillowben** [comment]
I like the test, looks pretty thorough.

**Pull request merged**
