### PR TITLE
fixed issues with rendering

### PR DESCRIPTION
**Pull request by weepingwillowben**

### CODE REVIEW

**Comment by weepingwillowben** [comment]
There is something very wrong here and I can't seem to figure it out...

**Comment by weepingwillowben** [comment]
@vwxyzjn There is something wrong. In my tests, the render is stalling or crashing depending on the circumstance and I don't know why. Since you have worked with rendering in vector environments before, can you take a look?

**Comment by weepingwillowben** [comment]
In particular, I seem to be getting sigabrts in pyglet when I used an environment which uses pyglet (almost any gym environment, like pendulum-v0), and otherwise it just hangs instead of exiting.

**Comment by vwxyzjn** [comment]
@weepingwillowben Hey sorry this is happening. So what if you initialize the env without using multi-processing (i.e. `num_cpus=0`), do you still see the crash?

**Comment by weepingwillowben** [comment]
No, without multiprocessing it works fine once I install the gym==1.7.3.

**Comment by vwxyzjn** [comment]
So with multiprocessing and `gym==1.7.3`, it breaks?

**Comment by weepingwillowben** [comment]
Yes. 
If I use space invaders as in the test here: https://github.com/PettingZoo-Team/SuperSuit/blob/c439b2858626f95564e493ccbb95fb55846d313c/test/test_vector/test_render.py or Pistonball it hangs for some reason.
If I use Pendulum-v0 or LunarLander-v2 it throws an error in the multiprocessing Queue object somehow.

**Comment by vwxyzjn** [comment]
Hey sorry for the delay. I had just tried out the test file using the `vec_env_test` branch

image

It would appear it only hangs on `test_vector_render_multiproc_human()` because the window wasn't properly closed. I will look into this further.

**Comment by vwxyzjn** [comment]
It's also interesting that it only hangs if `test_vector_render_multiproc_human()` is called after `test_vector_render_multiproc()`

image

**Comment by weepingwillowben** [comment]
@vwxyzjn  Thanks for taking the time to look into this. If you pull the latest version from master, you will see I use pistonball instead of Space invaders in the tests. The reason is because gym atari environments are a particularly easy case because it does not open a window in rgb_array mode [source](https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py#L147). However, many environments, such as pistonball or gym's classic control environments, do open a window.

**Comment by weepingwillowben** [comment]
Sorry, i meant the latest version from the `vec_env_test` branch

**Comment by vwxyzjn** [comment]
Hey I don't have direct access to edit the PR, but one fix I found was helpful was doing

```
    def close(self):
        for idx, pipe in enumerate(self.pipes):
            pipe.send("close")
            try:
                pipe.recv()
            except EOFError:
                print("end")
```

Unfortunately, it seems problematic to run all of these test functions in the same file (see example error below). When running each of these functions separately in a terminal has worked fine for me after the fix above.

```
(base) ~/.../vwxyzjn/SuperSuit >>> python test.py                                                                                                                    
end
WARNING:pettingzoo.utils.env_logger:[WARNING]: Called close on an unrendered environment.
WARNING:pettingzoo.utils.env_logger:[WARNING]: Called close on an unrendered environment.
XIO:  fatal IO error 0 (Success) on X server ":1"
      after 229 requests (229 known processed) with 0 events remaining.
```

Apparently closing the renderer and then try to open it again causes it to crash.

**Comment by weepingwillowben** [comment]
These tips helped, thanks.

I think the problem is that the x server gets horribly confused when different forked processes of the same base process try to open up windows. 

So I removed the bit in the multiprocessing constructor which renders the window, and just had it pipe the output image over the Queue. 

The try: except: block did not work as sometimes it segfaults the main process instead of the subprocess (which is what was raising the error). 

Finally, I just removed most of the tests, as that appeared to be necessary.

**Comment by weepingwillowben** [comment]
I ended up having to remove all the tests. But I think it is working as well as it can be expected to, given whatever low level nonsense is going on.

**Pull request merged**
